### ISSUE TITLE
Data to run

### ISSUE THREAD

**Issue by dougian** [dapascual/DirectedBeamSearch#1]
Could you upload a sample dataset that this was run with?  I want to try this over my own dataset but not sure that the formatting of the files has to be.

Thanks and great work!

**Comment by dapascual** [comment]
Hi, I just added the word sets used in the first experiments in the paper (data/word_sets.txt). The file contains 50 sets of 5 common English words. You can use the script encode_keywords.py to encode the words to glove, this way the code runs faster. I also added a small explanation. I'm still actively working in this code and I will add more information and examples soon. Thanks for your interest!
